#!/bin/bash
# Script to create GitHub release v5.0.3

echo "Creating GitHub Release v5.0.3..."
echo ""
echo "Option 1: Using GitHub Web Interface (Recommended)"
echo "=================================================="
echo "1. Go to: https://github.com/xelth-com/eckSnapshot/releases/new"
echo "2. Tag: v5.0.3"
echo "3. Title: Release v5.0.3 - Major Feature Update"
echo "4. Copy-paste content from: RELEASE_NOTES_v5.0.3.md"
echo "5. Click 'Publish release'"
echo ""
echo "Option 2: Using GitHub CLI (if installed)"
echo "=========================================="
echo "gh release create v5.0.3 \\"
echo "  --title 'Release v5.0.3 - Major Feature Update' \\"
echo "  --notes-file RELEASE_NOTES_v5.0.3.md"
echo ""
echo "Option 3: Using curl with GitHub API"
echo "====================================="
echo "You need a GitHub Personal Access Token with 'repo' scope."
echo ""
echo "curl -X POST \\"
echo "  -H 'Accept: application/vnd.github+json' \\"
echo "  -H 'Authorization: Bearer YOUR_GITHUB_TOKEN' \\"
echo "  https://api.github.com/repos/xelth-com/eckSnapshot/releases \\"
echo "  -d @- << 'JSON'"
echo "{"
echo "  \"tag_name\": \"v5.0.3\","
echo "  \"name\": \"Release v5.0.3 - Major Feature Update\","
echo "  \"body\": \"$(cat /tmp/release_body.md | jq -Rs .)\","
echo "  \"draft\": false,"
echo "  \"prerelease\": false"
echo "}"
echo "JSON"
echo ""
echo "Quick link to create release:"
echo "https://github.com/xelth-com/eckSnapshot/releases/new?tag=v5.0.3&title=Release+v5.0.3+-+Major+Feature+Update"
